name: '[build] i18n update'

on:
  pull_request:
    branches: ['main']
    paths:
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'

permissions:
  contents: write

jobs:
  i18n-update:
    name: '[build] update translations'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build gjs

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          setup-node: 'true'

      - name: Update POT files
        run: yarn pot-generator

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
        with:
          commit_message: 'lang: update pot files'
          file_pattern: 'po/*.po po/*.pot'

      - name: Clean up credentials
        if: always()
        run: |
          rm -rf ~/.gnupg ~/.gnupg/private-keys-v1.d || true
          find ~/.gnupg -delete 2>/dev/null || true
