name: '[ci] pr checks'

on:
  pull_request:
    branches: ['main']

permissions: {}

jobs:
  format:
    name: '[ci] check format'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          setup-node: 'true'

      - name: Run Format Check
        run: yarn format

  lint:
    name: '[ci] check lint'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          setup-node: 'true'

      - name: Run Lint
        run: yarn lint

  test-and-coverage:
    name: '[ci] test and coverage'
    uses: ./.github/workflows/test-coverage.yml
