name: '[ci] quality checks'

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */15 * *'

jobs:
  test-and-coverage:
    name: '[ci] test and coverage'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Setup Project
        uses: andrepg/do-it/.github/actions/setup-project
        with:
          setup-node: 'true'

      - name: Run Coverage
        run: yarn test:coverage

      - uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: tests/coverage/lcov.info
