name: '[reuse] test and coverage'

on: workflow_call

jobs:
  test-and-coverage:
    name: '[ci] test and coverage'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Project
        uses: ./.github/actions/setup-project
        with:
          setup-node: 'true'

      - name: Run Coverage
        run: yarn test:coverage

      - uses: qltysh/qlty-action/coverage@9e8e09d
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: tests/coverage/lcov.info
